Fix/autoware
tier4/edge_auto_launch pull request #26
Opened 2024-09-04 00:11 UTC by amc-nu

## PR Type
- Improvement

## Description

This PR updates the `edge_auto_launch` launch files to match the new autoware naming scheme introduced in version 2024.07.

## Review Procedure

Launch the system as usual following the README instructions.

## Pre-Review Checklist for the PR Author

**PR Author should check the checkboxes below when creating the PR.**

- [ ] Assign PR to reviewer

## Checklist for the PR Reviewer

**Reviewers should check the checkboxes below before approval.**

- [ ] Commits are properly organized and messages are according to the guideline
- [ ] (Optional) Unit tests have been written for new behavior
- [ ] PR title describes the changes

## Post-Review Checklist for the PR Author

**PR Author should check the checkboxes below before merging.**

- [ ] All open points are addressed and tracked via issues or tickets

## CI Checks

- **Build and test for PR**: Required to pass before the merge.

2024-09-04 11:46 UTC, manato requested changes
@amc-nu @a-yyg 
I left some comments on this PR. I'd appreciate it if you guys consider them.

2024-09-04 11:46 UTC, manato commented on edge_auto_launch/config/centerpoint_models/pts_backbone_neck_head_centerpoint.onnx
@a-yyg @amc-nu 
First of all, I really appreciate your updating this repository. 
I would propose to avoid this kind of ONNXs on this repository because of their size. Besides, the modification of [edge-auto side PR](https://github.com/tier4/edge-auto/pull/19) contains a role to download similar ONNX files, I'd appreciate it if you guys remove ONNX files from this PR.

2024-09-04 11:46 UTC, manato commented on edge_auto_launch/launch/component/lidar_centerpoint.launch.xml
> +  <arg name="model_path" default="$(find-pkg-share edge_auto_launch)/config/centerpoint_models"/>
```suggestion
  <arg name="model_path" default="$(env HOME)/autoware_data/lidar_centerpoint"/>
```
Would you mind to change the default root directory of ONNXs because they will be downloaded by the setup ansible?

2024-09-05 00:00 UTC, closed without merging

2024-09-05 00:09 UTC, amc-nu commented
@manato Apologies, I force-pushed the other branch and caused an issue with the history by accident. I moved the PR to https://github.com/tier4/edge_auto_launch/pull/27
Can you please continue the review over there?

2024-09-05 00:10 UTC, amc-nu commented on edge_auto_launch/launch/component/lidar_centerpoint.launch.xml
> +  <arg name="model_path" default="$(find-pkg-share edge_auto_launch)/config/centerpoint_models"/>
Attended here: https://github.com/tier4/edge_auto_launch/pull/27/files#diff-be19f460e2011a10671b5de9373823432114fbaa90601aa277b9fa253fa56fa2R5

2024-09-05 00:10 UTC, amc-nu commented on edge_auto_launch/config/centerpoint_models/pts_backbone_neck_head_centerpoint.onnx
Filed removed in https://github.com/tier4/edge_auto_launch/pull/27